const books=[['Genesis',50],['Exodus',40],['Leviticus',27],['Numbers',36],['Deuteronomy',34],['Joshua',24],['Judges',21],['Ruth',4],['1 Samuel',31],['2 Samuel',24],['1 Kings',22],['2 Kings',25],['1 Chronicles',29],['2 Chronicles',36],['Ezra',10],['Nehemiah',13],['Esther',10],['Job',42],['Psalms',150],['Proverbs',31],['Ecclesiastes',12],['Song of Solomon',8],['Isaiah',66],['Jeremiah',52],['Lamentations',5],['Ezekiel',48],['Daniel',12],['Hosea',14],['Joel',3],['Amos',9],['Obadiah',1],['Jonah',4],['Micah',7],['Nahum',3],['Habakkuk',3],['Zephaniah',3],['Haggai',2],['Zechariah',14],['Malachi',4],['Matthew',28],['Mark',16],['Luke',24],['John',21],['Acts',28],['Romans',16],['1 Corinthians',16],['2 Corinthians',13],['Galatians',6],['Ephesians',6],['Philippians',4],['Colossians',4],['1 Thessalonians',5],['2 Thessalonians',3],['1 Timothy',6],['2 Timothy',4],['Titus',3],['Philemon',1],['Hebrews',13],['James',5],['1 Peter',5],['2 Peter',3],['1 John',5],['2 John',1],['3 John',1],['Jude',1],['Revelation',22]];
const genesis=[
{t:'Creation',r:'Genesis 1–2',s:'God creates the heavens and the earth, fills creation with life, and creates humanity in His image. The story establishes the world as God’s creation and introduces Adam and Eve.',d:'Genesis opens with God as Creator. The repeated pattern of God speaking and creation responding establishes His authority. Humanity is created in God’s image and given responsibility within creation. Genesis 2 narrows the focus to the garden, Adam, Eve, work, relationship, and the command concerning the tree of the knowledge of good and evil.'},
{t:'Adam & Eve and the Fall',r:'Genesis 2–3',audio:'garden.mp3',detail:'garden.mp3',s:'Adam and Eve live in Eden, but the serpent challenges God’s command. They eat from the forbidden tree, hide from God, and the consequences of sin enter the story.',d:'The story moves from the goodness of Eden to humanity’s first act of disobedience. The serpent questions God’s words, Eve and Adam eat, and shame and blame follow. God confronts each participant, announces consequences, and sends the humans from Eden. Even here, the larger biblical story begins moving toward restoration.'},
{t:'Cain & Abel',r:'Genesis 4',s:'The first brothers bring offerings to God. Cain becomes angry when Abel’s offering is regarded favorably, ignores God’s warning, and kills his brother.',d:'Genesis 4 shows sin spreading beyond Eden into human relationships. God warns Cain that sin is crouching at the door and must be mastered, but Cain murders Abel. God confronts Cain, judges him, and also places a protective mark on him. The chapter then traces Cain’s descendants and contrasts them with the line through Seth.'},
{t:'From Adam to Noah',r:'Genesis 5',s:'A genealogy carries the story from Adam’s family to Noah, showing generations passing while keeping the promise-line moving forward.',d:'This chapter can look like a list of names, but it connects the earliest human story to Noah. The repeated phrase about death reinforces the consequences introduced in Genesis 3, while Enoch’s unusual description stands out. The chapter ends by introducing Noah and his sons.'},
{t:'Noah & the Flood',r:'Genesis 6–9',audio:'noah.mp3',detail:'noah.mp3',s:'Human violence and corruption increase. God tells Noah to build an ark, preserves Noah’s family and the animals through the flood, and afterward establishes a covenant marked by the rainbow.',d:'Genesis 6–9 is one continuous movement: corruption, judgment, preservation, a new beginning, and covenant. Noah obeys the ark instructions, the flood comes, and the waters eventually recede. Noah worships after leaving the ark. God promises not to destroy the earth by flood again and gives the rainbow as the covenant sign. The story also makes clear that the human heart still needs redemption.'},
{t:'Nations After the Flood',r:'Genesis 10',s:'Noah’s descendants spread into families and nations, setting up the peoples and places that appear later in the Bible.',d:'Often called the Table of Nations, Genesis 10 explains the spread of Noah’s descendants. These names become important later because Israel will encounter many of these peoples. It is background Tea that helps the rest of Genesis and the Old Testament make more sense.'},
{t:'Tower of Babel',r:'Genesis 11:1–9',s:'People gather to build a city and tower for their own name. God confuses their language and scatters them across the earth.',d:'Babel explains the scattering of peoples and languages. The builders seek security and fame on their own terms. God disrupts the project, and the narrative immediately begins narrowing from the nations to one family through whom blessing will come.'},
{t:'From Shem to Abram',r:'Genesis 11:10–32',s:'A genealogy carries the story from Shem to Terah and introduces Abram, Sarai, and Lot—the family at the center of the next major section.',d:'This connecting section matters because Genesis is about to shift dramatically. The broad story of humanity narrows to Abram’s family. Sarai’s barrenness is mentioned before God’s promises, setting up one of the major tensions of Abraham’s story.'},
{t:'Abraham: Called to Go',r:'Genesis 12–25',audio:'abraham.mp3',detail:'abraham.mp3',s:'God calls Abram to leave home and promises land, descendants, and blessing. Abraham’s long story follows faith, fear, family conflict, covenant, waiting, and the birth of Isaac.',d:'Abraham’s story spans many chapters because the promise unfolds slowly. Major moments include the call in Genesis 12, separation from Lot, covenant promises, Hagar and Ishmael, the covenant sign, Sodom and Gomorrah, Isaac’s birth, the testing in Genesis 22, Sarah’s death, and the search for Isaac’s wife. The point is not that Abraham never fails, but that God continues moving His covenant promise forward.'},
{t:'Isaac, Rebekah, Jacob & Esau',r:'Genesis 24–36',s:'The covenant family continues through Isaac and Rebekah, then their sons Jacob and Esau. Rivalry, deception, marriages, children, conflict, and reconciliation shape the next generation.',d:'This large family section connects Abraham to the twelve tribes of Israel. Jacob receives the birthright and blessing amid family conflict, leaves home, encounters God, works for Laban, marries Leah and Rachel, becomes father to a large family, and eventually returns. His name is changed to Israel, making the connection to the nation explicit.'},
{t:'Joseph and His Family',r:'Genesis 37–50',audio:'joseph.mp3',detail:'joseph.mp3',s:'Joseph is sold by his brothers, taken to Egypt, falsely accused, imprisoned, and eventually elevated to power. A famine brings his family to Egypt, where reconciliation and preservation follow.',d:'Joseph’s story explains how Jacob’s family ends up in Egypt—the exact setup Exodus needs. Dreams, betrayal, slavery, integrity, false accusation, prison, interpretation, famine planning, testing of the brothers, forgiveness, and family reunion all fit together. Genesis closes with the family in Egypt and Joseph expressing confidence that God will eventually bring them back to the promised land.'}
];
const quiz=[['What did God create humanity in?',['His image','The image of angels','The image of kings','No particular image'],0],['Which chapters open the Creation story?',['Genesis 1–2','Genesis 10–11','Exodus 1–2','Matthew 1–2'],0],['What does Genesis 2 focus on more closely?',['The garden, Adam and Eve','The flood','Abraham’s journey','Joseph in Egypt'],0]];
const state=JSON.parse(localStorage.getItem('btState')||'{"bookmarks":[],"notes":{},"highlights":{},"progress":[]}'); function save(){localStorage.setItem('btState',JSON.stringify(state));renderMy()}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.getElementById('acctBtn').onclick=()=>show('my');
const bs=document.getElementById('bookSel'),cs=document.getElementById('chapterSel'),vs=document.getElementById('verseSel');books.forEach(([b])=>bs.add(new Option(b,b)));function chapters(){cs.innerHTML='';let n=books.find(x=>x[0]===bs.value)[1];for(let i=1;i<=n;i++)cs.add(new Option('Chapter '+i,i));verses()}function verses(){vs.innerHTML='';for(let i=1;i<=60;i++)vs.add(new Option('Verse '+i,i))}bs.onchange=chapters;cs.onchange=verses;chapters();
async function openRef(ref){show('bible');let reader=document.getElementById('reader');reader.innerHTML='<div class="empty"><h3>Opening '+ref+'…</h3><p>Loading the public-domain KJV text.</p></div>';try{let res=await fetch('https://bible-api.com/'+encodeURIComponent(ref)+'?translation=kjv');if(!res.ok)throw 0;let d=await res.json();reader.innerHTML='<p class="eyebrow">KING JAMES VERSION</p><h2>'+d.reference+'</h2><p style="color:var(--muted)">Tap a verse for study tools.</p>'+d.verses.map(v=>`<div class="verse" data-ref="${v.book_name} ${v.chapter}:${v.verse}"><sup>${v.verse}</sup> ${v.text.trim()}</div><div class="verse-tools"><button data-act="highlight">Highlight</button><button data-act="bookmark">Bookmark</button><button data-act="note">Note</button><button data-act="tea">Get the Tea</button></div>`).join('');bindVerses()}catch(e){reader.innerHTML='<div class="empty"><h3>I couldn’t load that passage.</h3><p>This prototype loads the public-domain KJV from an online Bible service, so it needs internet access. Check the reference and try again.</p></div>'}}
function bindVerses(){document.querySelectorAll('.verse').forEach(v=>{if(state.highlights[v.dataset.ref])v.innerHTML='<mark>'+v.innerHTML+'</mark>';v.onclick=()=>{document.querySelectorAll('.verse').forEach(x=>x.classList.remove('selected'));v.classList.add('selected')};let tools=v.nextElementSibling;tools.querySelectorAll('button').forEach(b=>b.onclick=()=>tool(b.dataset.act,v))})}
let noteRef='';function tool(a,v){let r=v.dataset.ref;if(a==='highlight'){state.highlights[r]=!state.highlights[r];save();openRef(r.split(':')[0])}if(a==='bookmark'){if(!state.bookmarks.includes(r))state.bookmarks.push(r);save()}if(a==='note'){noteRef=r;document.getElementById('noteTitle').textContent='Note on '+r;document.getElementById('noteText').value=state.notes[r]||'';document.getElementById('noteDialog').showModal()}if(a==='tea'){show('tea');renderTea('Genesis')}}document.getElementById('saveNote').onclick=()=>{state.notes[noteRef]=document.getElementById('noteText').value;save()};
document.getElementById('goRef').onclick=()=>openRef(`${bs.value} ${cs.value}:${vs.value}`);document.getElementById('searchRef').onclick=()=>openRef(document.getElementById('refSearch').value.trim());document.getElementById('refSearch').onkeydown=e=>{if(e.key==='Enter')openRef(e.target.value.trim())};
const tabs=document.getElementById('bookTabs');function makeTabs(filter=''){tabs.innerHTML='';books.filter(x=>x[0].toLowerCase().includes(filter.toLowerCase())).forEach(([b])=>{let x=document.createElement('button');x.textContent=b;x.onclick=()=>renderTea(b);tabs.append(x)})}makeTabs();document.getElementById('teaBookSearch').oninput=e=>makeTabs(e.target.value);
function renderTea(book){
 document.querySelectorAll('#bookTabs button').forEach(x=>x.classList.toggle('active',x.textContent===book));
 let c=document.getElementById('teaContent');
 if(book!=='Genesis'){
  c.innerHTML=`<p class='eyebrow'>${book}</p><h2>${book} Bible Tea</h2><div class='quick'><h3>Tea is brewing</h3><p>The Bible reader is ready for ${book}. The Bible Tea story guide will be added book by book so it stays accurate and easy to use.</p><button onclick="openRef('${book} 1')">Read ${book} in the Bible</button></div>`;return;
 }
 c.innerHTML=`<p class='eyebrow'>Genesis</p><h2>In the beginning…</h2><p>Choose a story. You will get one clean page with the Quick Tea, All the Tea, Scripture link, audio when available, and your check-in.</p><div class='story-grid'>${genesis.map((g,i)=>`<button class='story-card' onclick='openTea(${i})'><small>${g.r}</small><strong>${g.t}</strong><span>${g.s.length>145?g.s.slice(0,145)+'…':g.s}</span></button>`).join('')}</div>`;
}
window.openTea=i=>{
 let g=genesis[i],c=document.getElementById('teaContent');
 c.innerHTML=`<div class='tea-detail'><button class='back-btn' onclick="renderTea('Genesis')">← Back to Genesis</button><p class='eyebrow'>${g.r}</p><h2>${g.t}</h2><section class='quick'><h3>Quick Tea</h3><p>${g.s}</p>${g.audio?`<audio controls preload='metadata' src='audio/${g.audio}'></audio>`:`<p style='color:var(--muted);font-size:.88rem'>Audio will be added here when this Tea is recorded.</p>`}</section><section class='alltea'><h3>All the Tea</h3><p>${g.d}</p>${g.detail?`<audio controls preload='metadata' src='detail-audio/${g.detail}'></audio>`:''}</section><div class='actions'><button onclick="openRef('${g.r.replace('–','-')}')">Read it in the Bible</button><button class='secondary' onclick='quizMe(${i})'>So, let me make sure I got this right…</button></div><div id='quiz${i}'></div></div>`;
 scrollTo(0,0);
}
window.quizMe=i=>{let box=document.getElementById('quiz'+i);let qs=i===0?quiz:[[ `Which passage is this Tea covering?`,[genesis[i].r,'Genesis 1–2','Matthew 5','Revelation 22'],0],[`What is this Tea mainly about?`,[genesis[i].t,'A different Bible book','A modern event','A church tradition'],0],[`Where can you verify the story?`,['In the Scripture passage shown','Only in the quiz','Only in the audio','Nowhere'],0]];box.className='quiz';box.innerHTML='<h3>So, let me make sure I got this right…</h3>'+qs.map((q,n)=>`<div class='q'><b>${n+1}. ${q[0]}</b>${q[1].map((o,j)=>`<button onclick="answer(this,${j===q[2]})">${o}</button>`).join('')}</div>`).join('');if(!state.progress.includes(genesis[i].t))state.progress.push(genesis[i].t);save()};window.answer=(b,ok)=>{b.classList.add(ok?'good':'bad');b.textContent+=(ok?' — Yep, you got the Tea!':' — Not quite. Try that one again.')};renderTea('Genesis');
function renderMy(){let h=Object.keys(state.highlights).filter(k=>state.highlights[k]);document.getElementById('myStats').innerHTML=`<article><h3>${state.bookmarks.length}</h3><p>Bookmarks</p></article><article><h3>${h.length}</h3><p>Highlights</p></article><article><h3>${state.progress.length}</h3><p>Tea sections started</p></article>`;document.getElementById('bookmarks').innerHTML=state.bookmarks.map(x=>`<div class='saved-item'>${x}</div>`).join('')||'<p>No bookmarks yet.</p>';document.getElementById('notes').innerHTML=Object.entries(state.notes).map(([r,n])=>`<div class='saved-item'><b>${r}</b><br>${n}</div>`).join('')||'<p>No notes yet.</p>';document.getElementById('progress').innerHTML=state.progress.map(x=>`<div class='saved-item'>✓ ${x}</div>`).join('')||'<p>No Tea progress yet.</p>'}renderMy();
