const books=['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra','Nehemiah','Esther','Job','Psalms','Proverbs','Ecclesiastes','Song of Solomon','Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation'];
const genesis=[['Creation','Genesis 1–2'],['Adam & Eve','Genesis 2–3'],['Cain & Abel','Genesis 4'],['From Adam to Noah','Genesis 5'],['Noah & the Ark','Genesis 6–9'],['Nations after the Flood','Genesis 10'],['Tower of Babel','Genesis 11'],['Abraham is Called','Genesis 12'],['Abraham, Sarah & the Wait','Genesis 15–22'],['Isaac & Rebekah','Genesis 24–26'],['Jacob & Esau','Genesis 25–28'],['Leah, Rachel & Laban','Genesis 29–31'],['Jacob Returns Home','Genesis 32–35'],['Joseph’s Family Drama','Genesis 37–50']];
let state={view:'welcome',book:'Genesis',story:null,mode:'quick',mobile:'left'};
const cover=document.getElementById('coverView'),bookView=document.getElementById('bookView'),L=document.getElementById('leftPage'),R=document.getElementById('rightPage'),crumb=document.getElementById('crumb');
function openBook(){cover.classList.remove('active');bookView.classList.add('active');render()}
document.querySelector('[data-go="welcome"]').onclick=openBook;
function renderTabs(){const n=document.getElementById('bookTabs');n.innerHTML='';books.forEach(b=>{let x=document.createElement('button');x.textContent=b;x.title=b;x.className=b===state.book?'active':'';x.onclick=()=>{state={...state,view:'book',book:b,story:null};render()};n.appendChild(x)})}
function welcome(){L.innerHTML=`<div class="eyebrow">WELCOME TO</div><h2>Bible <span class="script">Tea</span></h2><p class="quote">“We’re not rushing through the Bible. We’re sitting down, getting the context, and finding out how we got here.”</p><div class="rule"></div><h3>How to Use This Book</h3><div class="guide"><div class="guide-card"><b>Quick Tea</b><br>The short, conversational summary.</div><div class="guide-card"><b>All the Tea</b><br>The details, people, choices, consequences and connections.</div><div class="guide-card"><b>Hear Me Tell It</b><br>Listen in Kayla’s Bible Tea voice where audio is available.</div><div class="guide-card"><b>Read the Bible</b><br>Open the matching NKJV passage from an authorized Bible site.</div></div>`;
R.innerHTML=`<div class="eyebrow">BEFORE WE START</div><h2>The Bible Tea <span class="script">Key</span></h2><div class="tea-key"><div class="keyrow"><span class="dot hot"></span><div><b>Hot Tea</b><br>Drama, betrayal, conflict and major turning points.</div></div><div class="keyrow"><span class="dot good"></span><div><b>Good Tea</b><br>Victory, blessing, restoration and faith-filled moments.</div></div><div class="keyrow"><span class="dot important"></span><div><b>Important Tea</b><br>Teachings, commands, covenants and warnings.</div></div><div class="keyrow"><span class="dot background"></span><div><b>Background Tea</b><br>History, genealogy and context that keeps you from getting lost.</div></div><div class="keyrow"><span class="dot connecting"></span><div><b>Connecting Tea</b><br>The bridge that explains how one part of the story leads to the next.</div></div></div><div class="rule"></div><button class="gold-btn" onclick="state.view='book';state.book='Genesis';render()">START THE TEA · GENESIS</button>`;crumb.textContent='How to Use Bible Tea'}
function bookPage(){const b=state.book;const isGen=b==='Genesis';L.innerHTML=`<div class="eyebrow">${books.indexOf(b)<39?'OLD TESTAMENT':'NEW TESTAMENT'} · BOOK ${books.indexOf(b)+1}</div><h2>${b}</h2><p class="quote">${isGen?'The beginning of the world, the beginning of a family, and the beginning of a promise. We are taking it one story at a time so nobody has to wonder how we got from here to there.':`Welcome to ${b}. This book is one divider in the larger Bible Tea journey—not one tiny summary pretending the whole book is covered.`}</p><div class="rule"></div><h3>How we got here</h3><p class="copy">${isGen?'This is where the journey begins. Start with Creation and keep pressing Next Tea. Background and connecting entries are included so the story does not randomly jump ahead.':'This section is being mapped into individual stories, teachings, background and connecting Tea entries.'}</p>`;
let list=isGen?genesis:[[b+' introduction','Book overview']];R.innerHTML=`<div class="eyebrow">STORIES IN</div><h2>${b}</h2><div class="story-index">${list.map((s,i)=>`<a class="story-link" onclick="openStory('${s[0].replaceAll("'","\\'")}','${s[1]}')"><b>${i+1}. ${s[0]}</b><br><small>${s[1]}</small>${findOriginal(s[1],s[0])?'':' · <span class="brewing">TEA BREWING</span>'}</a>`).join('')}</div>`;crumb.textContent=b}
function findOriginal(ref,title){return ORIGINAL_STORIES.find(x=>x.ref===ref||x.title.toLowerCase().includes(title.toLowerCase().split(' ')[0]))}
window.openStory=(title,ref)=>{state.story={title,ref};state.view='story';state.mode='quick';render()}
function storyPage(){const {title,ref}=state.story;const o=findOriginal(ref,title);const full=(typeof FULL_STORIES!=='undefined'&&FULL_STORIES.find(x=>x.ref===ref||x.title.toLowerCase().includes(title.toLowerCase().split(' ')[0])));L.innerHTML=`<div class="eyebrow">${state.book} · ${ref}</div><h2>${title}</h2><div class="pillbar"><button class="${state.mode==='quick'?'active':''}" onclick="state.mode='quick';render()">Quick Tea</button><button class="${state.mode==='full'?'active':''}" onclick="state.mode='full';render()">All the Tea</button></div><article class="copy">${o?(state.mode==='quick'?`<p>${o.recap}</p><p><b>Takeaway:</b> ${o.takeaway}</p>`:(full?full.paragraphs.map(p=>`<p>${p}</p>`).join(''):`<p>${o.recap}</p><p>${o.takeaway}</p>`)):`<p><b>Tea Brewing.</b> This entry has its place in the journey, but its full Bible Tea treatment has not been written yet.</p>`}</article>${o?`<div class="audio-card"><b>Hear Me Tell It</b><audio controls src="${state.mode==='full'?'detail-audio/'+o.audio.split('/').pop():o.audio}"></audio></div>`:''}<a class="scripture-link" target="_blank" rel="noopener" href="https://www.biblegateway.com/passage/?search=${encodeURIComponent(ref)}&version=NKJV">Read Full NKJV ↗</a>`;
R.innerHTML=`<div class="eyebrow">DON'T GET LOST</div><h2>Who’s Who & <span class="script">Connections</span></h2><div class="who"><b>Where we just came from</b><p>${state.book==='Genesis'?'We are moving through Genesis in order, keeping the family lines and transitions visible instead of skipping straight to famous stories.':'This entry connects to the Tea immediately before it.'}</p></div><div class="who"><b>Who’s Who</b><p>Character cards will appear here as each Tea entry is completed, with relationships, role in the story, and Scripture-supported traits.</p></div><div class="who"><b>What happens next</b><p>Use Next Tea below to continue without losing the storyline.</p></div>`;crumb.textContent=title}
function render(){renderTabs();if(state.view==='welcome')welcome();else if(state.view==='book')bookPage();else storyPage();const mobile=innerWidth<=760;L.classList.toggle('mobile-show',!mobile||state.mobile==='left');R.classList.toggle('mobile-show',!mobile||state.mobile==='right')}
document.getElementById('nextPage').onclick=()=>{if(innerWidth<=760&&state.mobile==='left'){state.mobile='right';render();return}if(state.view==='welcome'){state.view='book';state.book='Genesis';state.mobile='left';render();return}if(state.view==='book'&&state.book==='Genesis'){openStory(genesis[0][0],genesis[0][1]);return}if(state.view==='story'&&state.book==='Genesis'){let i=genesis.findIndex(x=>x[0]===state.story.title);if(i<genesis.length-1)openStory(genesis[i+1][0],genesis[i+1][1])}};
document.getElementById('prevPage').onclick=()=>{if(innerWidth<=760&&state.mobile==='right'){state.mobile='left';render();return}if(state.view==='book'){state.view='welcome';render();return}if(state.view==='story'){let i=genesis.findIndex(x=>x[0]===state.story.title);if(i>0)openStory(genesis[i-1][0],genesis[i-1][1]);else{state.view='book';render()}}};addEventListener('resize',render);render();
